using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
namespace ConsoleApplication1
{
    class design
    {
        public int x;
        public int y;

        public static void frame(int x, int y)
        {
            Console.ForegroundColor = ConsoleColor.Yellow;
            for (int i = 0; i <= 85; i++)
            {
                Console.SetCursorPosition(x, y);
                Console.Write("█");
                x++;
            }

            for (int i = 0; i <= 15; i++)
            {
                Console.SetCursorPosition(x, y);
                Console.Write("█");
                y--;
            }

            for (int i = 0; i <= 85; i++)
            {
                int y2 = 13;
                Console.SetCursorPosition(x - 85, y);
                Console.Write("█");
                x++;
            }
            for (int i = 0; i <= 16; i++)
            {
                Console.SetCursorPosition(x - 172, y + 16);
                Console.Write("█");
                y--;
            }

        }
        public static void person(bool draw, int x, int y)
        {
            if (draw == true)
            {
                Console.SetCursorPosition(x + 19, y);
                Console.WriteLine(",");
                Console.SetCursorPosition(x + 20, y);
                Console.WriteLine("#");
                Console.SetCursorPosition(x + 21, y);
                Console.WriteLine("#");
                Console.SetCursorPosition(x + 22, y);
                Console.WriteLine("#");
                Console.SetCursorPosition(x + 23, y);
                Console.WriteLine("#");
                Console.SetCursorPosition(x + 24, y);
                Console.WriteLine("#");
                Console.SetCursorPosition(x + 25, y);
                Console.WriteLine(",");
                Console.SetCursorPosition(x + 19, y + 1);
                Console.WriteLine("#");
                Console.SetCursorPosition(x + 20, y + 1);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 24, y + 1);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 25, y + 1);
                Console.WriteLine("#");
                Console.SetCursorPosition(x + 19, y + 2);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 21, y + 2);
                Console.WriteLine("e");
                Console.SetCursorPosition(x + 22, y + 2);
                Console.WriteLine("`");
                Console.SetCursorPosition(x + 24, y + 2);
                Console.WriteLine("`");
                Console.SetCursorPosition(x + 25, y + 2);
                Console.WriteLine("e");
                Console.SetCursorPosition(x + 27, y + 2);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 19, y + 3);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 21, y + 3);
                Console.WriteLine("u");
                Console.SetCursorPosition(x + 26, y + 3);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 19, y + 4);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 22, y + 4);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 26, y + 4);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 19, y + 5);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 20, y + 5);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 21, y + 5);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 22, y + 5);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 23, y + 5);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 25, y + 5);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 26, y + 5);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 10, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 11, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 12, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 14, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 15, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 16, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 17, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 19, y + 6);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 20, y + 6);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 26, y + 6);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 27, y + 6);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 28, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 29, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 30, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 31, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 33, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 34, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 35, y + 6);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 8, y + 7);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 9, y + 7);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 13, y + 7);
                Console.WriteLine("`");
                Console.SetCursorPosition(x + 14, y + 7);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 15, y + 7);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 16, y + 7);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 17, y + 7);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 18, y + 7);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 19, y + 7);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 20, y + 7);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 24, y + 7);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 25, y + 7);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 26, y + 7);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 27, y + 7);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 28, y + 7);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 29, y + 7);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 30, y + 7);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 31, y + 7);
                Console.WriteLine("`");
                Console.SetCursorPosition(x + 35, y + 7);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 36, y + 7);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 7, y + 8);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 14, y + 8);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 15, y + 8);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 16, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 17, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 18, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 19, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 20, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 21, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 22, y + 8);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 23, y + 8);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 24, y + 8);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 25, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 26, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 27, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 28, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 29, y + 8);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 31, y + 8);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 32, y + 8);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 39, y + 8);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 6, y + 9);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 8, y + 9);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 22, y + 9);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 23, y + 9);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 24, y + 9);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 38, y + 9);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 39, y + 9);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 4, y + 10);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 5, y + 10);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 8, y + 10);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 9, y + 10);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 10, y + 10);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 15, y + 10);
                Console.WriteLine("o");
                Console.SetCursorPosition(x + 17, y + 10);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 18, y + 10);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 19, y + 10);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 20, y + 10);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 22, y + 10);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 23, y + 10);
                Console.WriteLine("o");
                Console.SetCursorPosition(x + 28, y + 10);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 29, y + 10);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 31, y + 10);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 34, y + 10);
                Console.WriteLine("`");
                Console.SetCursorPosition(x + 36, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 1, y + 11);
                Console.WriteLine("(");
                Console.SetCursorPosition(x + 2, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 3, y + 11);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 7, y + 11);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 8, y + 11);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 9, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 11, y + 11);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 12, y + 11);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 13, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 14, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 15, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 16, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 17, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 18, y + 11);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 19, y + 11);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 21, y + 11);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 22, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 23, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 24, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 25, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 26, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 27, y + 11);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 29, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 31, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 32, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 33, y + 11);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 37, y + 11);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 38, y + 11);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 39, y + 11);
                Console.WriteLine(")");
                Console.SetCursorPosition(x + 1, y + 12);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 3, y + 12);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 5, y + 12);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 6, y + 12);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 7, y + 12);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 11, y + 12);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 12, y + 12);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 18, y + 12);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 19, y + 12);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 20, y + 12);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 21, y + 12);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 22, y + 12);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 28, y + 12);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 29, y + 12);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 33, y + 12);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 34, y + 12);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 35, y + 12);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 37, y + 12);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 38, y + 12);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 1, y + 13);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 4, y + 13);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 5, y + 13);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 6, y + 13);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 13, y + 13);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 14, y + 13);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 17, y + 13);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 18, y + 13);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 19, y + 13);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 20, y + 13);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 21, y + 13);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 22, y + 13);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 23, y + 13);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 26, y + 13);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 27, y + 13);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 34, y + 13);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 35, y + 13);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 36, y + 13);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 39, y + 13);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 1, y + 14);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 4, y + 14);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 6, y + 14);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 14, y + 14);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 16, y + 14);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 17, y + 14);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 18, y + 14);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 19, y + 14);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 20, y + 14);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 21, y + 14);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 22, y + 14);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 23, y + 14);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 26, y + 14);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 27, y + 14);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 34, y + 14);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 35, y + 14);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 36, y + 14);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 39, y + 14);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 1, y + 15);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 4, y + 15);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 6, y + 15);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 14, y + 15);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 16, y + 15);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 17, y + 15);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 18, y + 15);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 19, y + 15);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 20, y + 15);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 21, y + 15);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 22, y + 15);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 25, y + 15);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 33, y + 15);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 35, y + 15);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 38, y + 15);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 2, y + 16);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 4, y + 16);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 6, y + 16);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 14, y + 16);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 16, y + 16);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 17, y + 16);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 18, y + 16);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 19, y + 16);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 20, y + 16);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 21, y + 16);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 22, y + 16);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 23, y + 16);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 24, y + 16);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 25, y + 16);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 26, y + 16);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 28, y + 16);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 36, y + 16);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 38, y + 16);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 40, y + 16);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 4, y + 17);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 6, y + 17);
                Console.WriteLine("(");
                Console.SetCursorPosition(x + 14, y + 17);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 16, y + 17);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 17, y + 17);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 18, y + 17);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 19, y + 17);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 20, y + 17);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 22, y + 17);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 23, y + 17);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 24, y + 17);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 25, y + 17);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 26, y + 17);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 27, y + 17);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 28, y + 17);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 36, y + 17);
                Console.WriteLine(")");
                Console.SetCursorPosition(x + 40, y + 17);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 1, y + 18);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 2, y + 18);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 3, y + 18);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 4, y + 18);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 6, y + 18);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 7, y + 18);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 14, y + 18);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 19, y + 18);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 26, y + 18);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 33, y + 18);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 34, y + 18);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 36, y + 18);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 37, y + 18);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 38, y + 18);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 39, y + 18);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 2, y + 19);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 3, y + 19);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 4, y + 19);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 5, y + 19);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 6, y + 19);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 7, y + 19);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 9, y + 19);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 10, y + 19);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 16, y + 19);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 22, y + 19);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 30, y + 19);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 36, y + 19);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 36, y + 19);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 37, y + 19);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 38, y + 19);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 39, y + 19);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 40, y + 19);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 41, y + 19);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 42, y + 19);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 43, y + 19);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 1, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 2, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 3, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 4, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 5, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 13, y + 20);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 14, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 15, y + 20);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 16, y + 20);
                Console.WriteLine("L");
                Console.SetCursorPosition(x + 24, y + 20);
                Console.WriteLine("`");
                Console.SetCursorPosition(x + 25, y + 20);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 33, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 34, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 35, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 36, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 37, y + 20);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 8, y + 21);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 10, y + 21);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 1, y + 21);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 12, y + 21);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 13, y + 21);
                Console.WriteLine(",");
                Console.SetCursorPosition(x + 14, y + 21);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 15, y + 21);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 16, y + 21);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 17, y + 21);
                Console.WriteLine("`");
                Console.SetCursorPosition(x + 19, y + 21);
                Console.WriteLine("`");
                Console.SetCursorPosition(x + 20, y + 21);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 21, y + 21);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 22, y + 21);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 23, y + 21);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 24, y + 21);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 25, y + 21);
                Console.WriteLine("-");
                Console.SetCursorPosition(x + 26, y + 21);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 27, y + 21);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 8, y + 22);
                Console.WriteLine(";");
                Console.SetCursorPosition(x + 15, y + 22);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 21, y + 22);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 28, y + 22);
                Console.WriteLine(";");
                Console.SetCursorPosition(x + 8, y + 23);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 14, y + 23);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 22, y + 23);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 28, y + 23);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 8, y + 24);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 13, y + 24);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 23, y + 24);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 24, y + 24);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 28, y + 24);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 8, y + 25);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 9, y + 25);
                Console.WriteLine("`");
                Console.SetCursorPosition(x + 10, y + 25);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 11, y + 25);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 12, y + 25);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 24, y + 25);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 27, y + 25);
                Console.WriteLine(",");
                Console.SetCursorPosition(x + 28, y + 25);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 8, y + 26);
                Console.WriteLine("(");
                Console.SetCursorPosition(x + 9, y + 26);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 10, y + 26);
                Console.WriteLine(")");
                Console.SetCursorPosition(x + 12, y + 26);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 14, y + 26);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 15, y + 26);
                Console.WriteLine(")");
                Console.SetCursorPosition(x + 8, y + 27);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 12, y + 27);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 24, y + 27);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 28, y + 27);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 8, y + 28);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 10, y + 28);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 11, y + 28);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 12, y + 28);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 14, y + 28);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 26, y + 28);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 27, y + 28);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 28, y + 28);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 29, y + 28);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 31, y + 28);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 8, y + 29);
                Console.WriteLine(":");
                Console.SetCursorPosition(x + 9, y + 29);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 10, y + 29);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 11, y + 29);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 12, y + 29);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 25, y + 29);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 26, y + 29);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 26, y + 29);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 27, y + 29);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 28, y + 29);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 9, y + 30);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 12, y + 30);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 25, y + 30);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 27, y + 30);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 28, y + 30);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 30, y + 30);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 9, y + 31);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 10, y + 31);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 11, y + 31);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 12, y + 31);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 24, y + 31);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 26, y + 31);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 27, y + 31);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 28, y + 31);
                Console.WriteLine("'");
                Console.SetCursorPosition(x + 29, y + 31);
                Console.WriteLine("`");
                Console.SetCursorPosition(x + 30, y + 31);
                Console.WriteLine("8");
                Console.SetCursorPosition(x + 31, y + 31);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 32, y + 31);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 33, y + 31);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 9, y + 32);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 11, y + 32);
                Console.WriteLine("o");
                Console.SetCursorPosition(x + 12, y + 32);
                Console.WriteLine("o");
                Console.SetCursorPosition(x + 14, y + 32);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 26, y + 32);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 27, y + 32);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 28, y + 32);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 29, y + 32);
                Console.WriteLine(".");
                Console.SetCursorPosition(x + 30, y + 32);
                Console.WriteLine("/");
                Console.SetCursorPosition(x + 31, y + 32);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 32, y + 32);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 33, y + 32);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 34, y + 32);
                Console.WriteLine(")");
                Console.SetCursorPosition(x + 33, y + 33);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 33, y + 33);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 9, y + 33);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 10, y + 33);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 11, y + 33);
                Console.WriteLine("=");
                Console.SetCursorPosition(x + 12, y + 33);
                Console.WriteLine("|");
                Console.SetCursorPosition(x + 9, y + 34);
                Console.WriteLine("\\");
                Console.SetCursorPosition(x + 10, y + 34);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 11, y + 34);
                Console.WriteLine("_");
                Console.SetCursorPosition(x + 13, y + 34);
                Console.WriteLine("/");
            }
            else
            {
                Console.SetCursorPosition(x + 19, y);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 1);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 1);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 1);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 1);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 2);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 2);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 2);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 2);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 2);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 2);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 3);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 3);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 3);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 4);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 4);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 4);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 5);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 5);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 5);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 5);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 5);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 5);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 5);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 11, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 15, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 29, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 30, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 31, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 33, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 34, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 35, y + 6);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 13, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 15, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 18, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 29, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 30, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 31, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 35, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 36, y + 7);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 7, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 15, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 18, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 29, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 31, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 32, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 39, y + 8);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 6, y + 9);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 9);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 9);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 9);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 9);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 38, y + 9);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 39, y + 9);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 4, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 5, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 15, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 18, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 29, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 31, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 34, y + 10);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 35, y + 10);
                Console.WriteLine("");
                Console.SetCursorPosition(x + 1, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 2, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 3, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 7, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 11, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 13, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 15, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 18, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 29, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 31, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 32, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 33, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 37, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 38, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 39, y + 11);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 1, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 3, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 5, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 6, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 7, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 11, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 18, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 29, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 33, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 34, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 35, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 37, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 38, y + 12);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 1, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 4, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 5, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 6, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 13, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 18, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 13);
                Console.WriteLine("");
                Console.SetCursorPosition(x + 26, y + 13);
                Console.WriteLine("");
                Console.SetCursorPosition(x + 27, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 34, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 35, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 36, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 39, y + 13);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 1, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 4, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 6, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 18, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 34, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 35, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 36, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 39, y + 14);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 1, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 4, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 6, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 18, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 33, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 35, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 38, y + 15);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 2, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 4, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 6, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 18, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 36, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 38, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 40, y + 16);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 4, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 6, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 18, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 36, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 40, y + 17);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 1, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 2, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 3, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 4, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 6, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 7, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 33, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 34, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 36, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 37, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 38, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 39, y + 18);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 2, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 3, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 4, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 5, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 6, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 7, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 30, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 36, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 36, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 37, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 38, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 39, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 40, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 41, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 42, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 43, y + 19);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 1, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 2, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 3, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 4, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 5, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 13, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 15, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 33, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 34, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 35, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 36, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 37, y + 20);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 1, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 13, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 15, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 16, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 17, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 19, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 20, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 21);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 22);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 15, y + 22);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 21, y + 22);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 22);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 23);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 23);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 22, y + 23);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 23);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 24);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 13, y + 24);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 23, y + 24);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 24);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 24);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 25);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 25);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 25);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 11, y + 25);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 25);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 25);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 25);
                Console.WriteLine("");
                Console.SetCursorPosition(x + 28, y + 25);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 26);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 26);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 26);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 26);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 26);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 15, y + 26);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 27);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 27);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 27);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 27);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 28);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 28);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 11, y + 28);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 28);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 28);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 28);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 28);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 28);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 29, y + 28);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 31, y + 28);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 8, y + 29);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 29);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 29);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 11, y + 29);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 29);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 29);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 29);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 29);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 29);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 29);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 30);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 30);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 25, y + 30);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 30);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 30);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 30, y + 30);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 11, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 24, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 29, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 30, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 31, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 32, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 33, y + 31);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 11, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 14, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 26, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 27, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 28, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 29, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 30, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 31, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 32, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 33, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 34, y + 32);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 33, y + 33);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 33, y + 33);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 33);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 33);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 11, y + 33);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 12, y + 33);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 9, y + 34);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 10, y + 34);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 11, y + 34);
                Console.WriteLine(" ");
                Console.SetCursorPosition(x + 13, y + 34);
                Console.WriteLine(" ");



            
        }
        }
        public static void personAnimate()
        {
            ConsoleKeyInfo cki = Console.ReadKey();
            if (cki.Key == ConsoleKey.I)
                Console.ForegroundColor = ConsoleColor.Green;
            int x = 0;
            int y = 15;
            while (x < 33)
            {
                person(false, x, y);
                x++;
                person(true, x, y);
                Thread.Sleep(100);
            }
        }
        public static void yKey()
        {
            ConsoleKeyInfo cki = Console.ReadKey();
            if (cki.Key == ConsoleKey.Y)
            {
                int x = 33;
                int y = 15;
                while (x > 0)
                {
                    Console.ForegroundColor = ConsoleColor.Green;
                    person(false, x, y);
                    x--;
                    person(true, x, y);
                    Thread.Sleep(100);

                }

            }
        }
        public static void menu()
        {
            Console.SetCursorPosition(80, 4);
            Console.WriteLine("for move a person to the stoper press i ");
            Console.SetCursorPosition(110, 6);
            Console.WriteLine("for move a person back from the stoper press y");
        }
      
    }
}
