//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmiamStore.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Charge", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Charge : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardNumberField;
        
        private int AmountToChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CreditCardNumber {
            get {
                return this.CreditCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardNumberField, value) != true)) {
                    this.CreditCardNumberField = value;
                    this.RaisePropertyChanged("CreditCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AmountToCharge {
            get {
                return this.AmountToChargeField;
            }
            set {
                if ((this.AmountToChargeField.Equals(value) != true)) {
                    this.AmountToChargeField = value;
                    this.RaisePropertyChanged("AmountToCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StoreName {
            get {
                return this.StoreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreNameField, value) != true)) {
                    this.StoreNameField = value;
                    this.RaisePropertyChanged("StoreName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.payWebServiceSoap")]
    public interface payWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name holderName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmPay", ReplyAction="*")]
        AmiamStore.ServiceReference1.ConfirmPayResponse ConfirmPay(AmiamStore.ServiceReference1.ConfirmPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmPay", ReplyAction="*")]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.ConfirmPayResponse> ConfirmPayAsync(AmiamStore.ServiceReference1.ConfirmPayRequest request);
        
        // CODEGEN: Generating message contract since element name holderName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProperCardDetails", ReplyAction="*")]
        AmiamStore.ServiceReference1.ProperCardDetailsResponse ProperCardDetails(AmiamStore.ServiceReference1.ProperCardDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProperCardDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.ProperCardDetailsResponse> ProperCardDetailsAsync(AmiamStore.ServiceReference1.ProperCardDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name creditCardNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DiscountForMasterCardClients", ReplyAction="*")]
        AmiamStore.ServiceReference1.DiscountForMasterCardClientsResponse DiscountForMasterCardClients(AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DiscountForMasterCardClients", ReplyAction="*")]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.DiscountForMasterCardClientsResponse> DiscountForMasterCardClientsAsync(AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequest request);
        
        // CODEGEN: Generating message contract since element name holderName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientHasEnoghMoney", ReplyAction="*")]
        AmiamStore.ServiceReference1.ClientHasEnoghMoneyResponse ClientHasEnoghMoney(AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientHasEnoghMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.ClientHasEnoghMoneyResponse> ClientHasEnoghMoneyAsync(AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequest request);
        
        // CODEGEN: Generating message contract since element name creditCardNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetailtsOfAllInvites", ReplyAction="*")]
        AmiamStore.ServiceReference1.DetailtsOfAllInvitesResponse DetailtsOfAllInvites(AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetailtsOfAllInvites", ReplyAction="*")]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.DetailtsOfAllInvitesResponse> DetailtsOfAllInvitesAsync(AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequest request);
        
        // CODEGEN: Generating message contract since element name ToEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPurchaseClearanceOnEmail", ReplyAction="*")]
        AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailResponse SendPurchaseClearanceOnEmail(AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPurchaseClearanceOnEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailResponse> SendPurchaseClearanceOnEmailAsync(AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPay", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.ConfirmPayRequestBody Body;
        
        public ConfirmPayRequest() {
        }
        
        public ConfirmPayRequest(AmiamStore.ServiceReference1.ConfirmPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string holderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string creditCardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cvv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string expirityDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int amountToCharge;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public AmiamStore.ServiceReference1.Charge[] list;
        
        public ConfirmPayRequestBody() {
        }
        
        public ConfirmPayRequestBody(string holderName, string creditCardNumber, string cvv, string expirityDate, int amountToCharge, AmiamStore.ServiceReference1.Charge[] list) {
            this.holderName = holderName;
            this.creditCardNumber = creditCardNumber;
            this.cvv = cvv;
            this.expirityDate = expirityDate;
            this.amountToCharge = amountToCharge;
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPayResponse", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.ConfirmPayResponseBody Body;
        
        public ConfirmPayResponse() {
        }
        
        public ConfirmPayResponse(AmiamStore.ServiceReference1.ConfirmPayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmPayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ConfirmPayResult;
        
        public ConfirmPayResponseBody() {
        }
        
        public ConfirmPayResponseBody(bool ConfirmPayResult) {
            this.ConfirmPayResult = ConfirmPayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProperCardDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProperCardDetails", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.ProperCardDetailsRequestBody Body;
        
        public ProperCardDetailsRequest() {
        }
        
        public ProperCardDetailsRequest(AmiamStore.ServiceReference1.ProperCardDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProperCardDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string holderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string creditCardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cvv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string expirityDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int amountToCharge;
        
        public ProperCardDetailsRequestBody() {
        }
        
        public ProperCardDetailsRequestBody(string holderName, string creditCardNumber, string cvv, string expirityDate, int amountToCharge) {
            this.holderName = holderName;
            this.creditCardNumber = creditCardNumber;
            this.cvv = cvv;
            this.expirityDate = expirityDate;
            this.amountToCharge = amountToCharge;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProperCardDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProperCardDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.ProperCardDetailsResponseBody Body;
        
        public ProperCardDetailsResponse() {
        }
        
        public ProperCardDetailsResponse(AmiamStore.ServiceReference1.ProperCardDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProperCardDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ProperCardDetailsResult;
        
        public ProperCardDetailsResponseBody() {
        }
        
        public ProperCardDetailsResponseBody(bool ProperCardDetailsResult) {
            this.ProperCardDetailsResult = ProperCardDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DiscountForMasterCardClientsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DiscountForMasterCardClients", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequestBody Body;
        
        public DiscountForMasterCardClientsRequest() {
        }
        
        public DiscountForMasterCardClientsRequest(AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DiscountForMasterCardClientsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string creditCardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int amountToPay;
        
        public DiscountForMasterCardClientsRequestBody() {
        }
        
        public DiscountForMasterCardClientsRequestBody(string creditCardNumber, int amountToPay) {
            this.creditCardNumber = creditCardNumber;
            this.amountToPay = amountToPay;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DiscountForMasterCardClientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DiscountForMasterCardClientsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.DiscountForMasterCardClientsResponseBody Body;
        
        public DiscountForMasterCardClientsResponse() {
        }
        
        public DiscountForMasterCardClientsResponse(AmiamStore.ServiceReference1.DiscountForMasterCardClientsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DiscountForMasterCardClientsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DiscountForMasterCardClientsResult;
        
        public DiscountForMasterCardClientsResponseBody() {
        }
        
        public DiscountForMasterCardClientsResponseBody(int DiscountForMasterCardClientsResult) {
            this.DiscountForMasterCardClientsResult = DiscountForMasterCardClientsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientHasEnoghMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientHasEnoghMoney", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequestBody Body;
        
        public ClientHasEnoghMoneyRequest() {
        }
        
        public ClientHasEnoghMoneyRequest(AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientHasEnoghMoneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string holderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int amountToPay;
        
        public ClientHasEnoghMoneyRequestBody() {
        }
        
        public ClientHasEnoghMoneyRequestBody(string holderName, int amountToPay) {
            this.holderName = holderName;
            this.amountToPay = amountToPay;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientHasEnoghMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientHasEnoghMoneyResponse", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.ClientHasEnoghMoneyResponseBody Body;
        
        public ClientHasEnoghMoneyResponse() {
        }
        
        public ClientHasEnoghMoneyResponse(AmiamStore.ServiceReference1.ClientHasEnoghMoneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientHasEnoghMoneyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ClientHasEnoghMoneyResult;
        
        public ClientHasEnoghMoneyResponseBody() {
        }
        
        public ClientHasEnoghMoneyResponseBody(bool ClientHasEnoghMoneyResult) {
            this.ClientHasEnoghMoneyResult = ClientHasEnoghMoneyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetailtsOfAllInvitesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetailtsOfAllInvites", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequestBody Body;
        
        public DetailtsOfAllInvitesRequest() {
        }
        
        public DetailtsOfAllInvitesRequest(AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DetailtsOfAllInvitesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string creditCardNumber;
        
        public DetailtsOfAllInvitesRequestBody() {
        }
        
        public DetailtsOfAllInvitesRequestBody(string creditCardNumber) {
            this.creditCardNumber = creditCardNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetailtsOfAllInvitesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetailtsOfAllInvitesResponse", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.DetailtsOfAllInvitesResponseBody Body;
        
        public DetailtsOfAllInvitesResponse() {
        }
        
        public DetailtsOfAllInvitesResponse(AmiamStore.ServiceReference1.DetailtsOfAllInvitesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DetailtsOfAllInvitesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AmiamStore.ServiceReference1.Charge[] DetailtsOfAllInvitesResult;
        
        public DetailtsOfAllInvitesResponseBody() {
        }
        
        public DetailtsOfAllInvitesResponseBody(AmiamStore.ServiceReference1.Charge[] DetailtsOfAllInvitesResult) {
            this.DetailtsOfAllInvitesResult = DetailtsOfAllInvitesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPurchaseClearanceOnEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPurchaseClearanceOnEmail", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequestBody Body;
        
        public SendPurchaseClearanceOnEmailRequest() {
        }
        
        public SendPurchaseClearanceOnEmailRequest(AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendPurchaseClearanceOnEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ToEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ToName;
        
        public SendPurchaseClearanceOnEmailRequestBody() {
        }
        
        public SendPurchaseClearanceOnEmailRequestBody(string ToEmail, string ToName) {
            this.ToEmail = ToEmail;
            this.ToName = ToName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPurchaseClearanceOnEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPurchaseClearanceOnEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailResponseBody Body;
        
        public SendPurchaseClearanceOnEmailResponse() {
        }
        
        public SendPurchaseClearanceOnEmailResponse(AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendPurchaseClearanceOnEmailResponseBody {
        
        public SendPurchaseClearanceOnEmailResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface payWebServiceSoapChannel : AmiamStore.ServiceReference1.payWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class payWebServiceSoapClient : System.ServiceModel.ClientBase<AmiamStore.ServiceReference1.payWebServiceSoap>, AmiamStore.ServiceReference1.payWebServiceSoap {
        
        public payWebServiceSoapClient() {
        }
        
        public payWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public payWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public payWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public payWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmiamStore.ServiceReference1.ConfirmPayResponse AmiamStore.ServiceReference1.payWebServiceSoap.ConfirmPay(AmiamStore.ServiceReference1.ConfirmPayRequest request) {
            return base.Channel.ConfirmPay(request);
        }
        
        public bool ConfirmPay(string holderName, string creditCardNumber, string cvv, string expirityDate, int amountToCharge, AmiamStore.ServiceReference1.Charge[] list) {
            AmiamStore.ServiceReference1.ConfirmPayRequest inValue = new AmiamStore.ServiceReference1.ConfirmPayRequest();
            inValue.Body = new AmiamStore.ServiceReference1.ConfirmPayRequestBody();
            inValue.Body.holderName = holderName;
            inValue.Body.creditCardNumber = creditCardNumber;
            inValue.Body.cvv = cvv;
            inValue.Body.expirityDate = expirityDate;
            inValue.Body.amountToCharge = amountToCharge;
            inValue.Body.list = list;
            AmiamStore.ServiceReference1.ConfirmPayResponse retVal = ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).ConfirmPay(inValue);
            return retVal.Body.ConfirmPayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.ConfirmPayResponse> AmiamStore.ServiceReference1.payWebServiceSoap.ConfirmPayAsync(AmiamStore.ServiceReference1.ConfirmPayRequest request) {
            return base.Channel.ConfirmPayAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmiamStore.ServiceReference1.ConfirmPayResponse> ConfirmPayAsync(string holderName, string creditCardNumber, string cvv, string expirityDate, int amountToCharge, AmiamStore.ServiceReference1.Charge[] list) {
            AmiamStore.ServiceReference1.ConfirmPayRequest inValue = new AmiamStore.ServiceReference1.ConfirmPayRequest();
            inValue.Body = new AmiamStore.ServiceReference1.ConfirmPayRequestBody();
            inValue.Body.holderName = holderName;
            inValue.Body.creditCardNumber = creditCardNumber;
            inValue.Body.cvv = cvv;
            inValue.Body.expirityDate = expirityDate;
            inValue.Body.amountToCharge = amountToCharge;
            inValue.Body.list = list;
            return ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).ConfirmPayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmiamStore.ServiceReference1.ProperCardDetailsResponse AmiamStore.ServiceReference1.payWebServiceSoap.ProperCardDetails(AmiamStore.ServiceReference1.ProperCardDetailsRequest request) {
            return base.Channel.ProperCardDetails(request);
        }
        
        public bool ProperCardDetails(string holderName, string creditCardNumber, string cvv, string expirityDate, int amountToCharge) {
            AmiamStore.ServiceReference1.ProperCardDetailsRequest inValue = new AmiamStore.ServiceReference1.ProperCardDetailsRequest();
            inValue.Body = new AmiamStore.ServiceReference1.ProperCardDetailsRequestBody();
            inValue.Body.holderName = holderName;
            inValue.Body.creditCardNumber = creditCardNumber;
            inValue.Body.cvv = cvv;
            inValue.Body.expirityDate = expirityDate;
            inValue.Body.amountToCharge = amountToCharge;
            AmiamStore.ServiceReference1.ProperCardDetailsResponse retVal = ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).ProperCardDetails(inValue);
            return retVal.Body.ProperCardDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.ProperCardDetailsResponse> AmiamStore.ServiceReference1.payWebServiceSoap.ProperCardDetailsAsync(AmiamStore.ServiceReference1.ProperCardDetailsRequest request) {
            return base.Channel.ProperCardDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmiamStore.ServiceReference1.ProperCardDetailsResponse> ProperCardDetailsAsync(string holderName, string creditCardNumber, string cvv, string expirityDate, int amountToCharge) {
            AmiamStore.ServiceReference1.ProperCardDetailsRequest inValue = new AmiamStore.ServiceReference1.ProperCardDetailsRequest();
            inValue.Body = new AmiamStore.ServiceReference1.ProperCardDetailsRequestBody();
            inValue.Body.holderName = holderName;
            inValue.Body.creditCardNumber = creditCardNumber;
            inValue.Body.cvv = cvv;
            inValue.Body.expirityDate = expirityDate;
            inValue.Body.amountToCharge = amountToCharge;
            return ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).ProperCardDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmiamStore.ServiceReference1.DiscountForMasterCardClientsResponse AmiamStore.ServiceReference1.payWebServiceSoap.DiscountForMasterCardClients(AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequest request) {
            return base.Channel.DiscountForMasterCardClients(request);
        }
        
        public int DiscountForMasterCardClients(string creditCardNumber, int amountToPay) {
            AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequest inValue = new AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequest();
            inValue.Body = new AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequestBody();
            inValue.Body.creditCardNumber = creditCardNumber;
            inValue.Body.amountToPay = amountToPay;
            AmiamStore.ServiceReference1.DiscountForMasterCardClientsResponse retVal = ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).DiscountForMasterCardClients(inValue);
            return retVal.Body.DiscountForMasterCardClientsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.DiscountForMasterCardClientsResponse> AmiamStore.ServiceReference1.payWebServiceSoap.DiscountForMasterCardClientsAsync(AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequest request) {
            return base.Channel.DiscountForMasterCardClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmiamStore.ServiceReference1.DiscountForMasterCardClientsResponse> DiscountForMasterCardClientsAsync(string creditCardNumber, int amountToPay) {
            AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequest inValue = new AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequest();
            inValue.Body = new AmiamStore.ServiceReference1.DiscountForMasterCardClientsRequestBody();
            inValue.Body.creditCardNumber = creditCardNumber;
            inValue.Body.amountToPay = amountToPay;
            return ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).DiscountForMasterCardClientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmiamStore.ServiceReference1.ClientHasEnoghMoneyResponse AmiamStore.ServiceReference1.payWebServiceSoap.ClientHasEnoghMoney(AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequest request) {
            return base.Channel.ClientHasEnoghMoney(request);
        }
        
        public bool ClientHasEnoghMoney(string holderName, int amountToPay) {
            AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequest inValue = new AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequest();
            inValue.Body = new AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequestBody();
            inValue.Body.holderName = holderName;
            inValue.Body.amountToPay = amountToPay;
            AmiamStore.ServiceReference1.ClientHasEnoghMoneyResponse retVal = ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).ClientHasEnoghMoney(inValue);
            return retVal.Body.ClientHasEnoghMoneyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.ClientHasEnoghMoneyResponse> AmiamStore.ServiceReference1.payWebServiceSoap.ClientHasEnoghMoneyAsync(AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequest request) {
            return base.Channel.ClientHasEnoghMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmiamStore.ServiceReference1.ClientHasEnoghMoneyResponse> ClientHasEnoghMoneyAsync(string holderName, int amountToPay) {
            AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequest inValue = new AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequest();
            inValue.Body = new AmiamStore.ServiceReference1.ClientHasEnoghMoneyRequestBody();
            inValue.Body.holderName = holderName;
            inValue.Body.amountToPay = amountToPay;
            return ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).ClientHasEnoghMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmiamStore.ServiceReference1.DetailtsOfAllInvitesResponse AmiamStore.ServiceReference1.payWebServiceSoap.DetailtsOfAllInvites(AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequest request) {
            return base.Channel.DetailtsOfAllInvites(request);
        }
        
        public AmiamStore.ServiceReference1.Charge[] DetailtsOfAllInvites(string creditCardNumber) {
            AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequest inValue = new AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequest();
            inValue.Body = new AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequestBody();
            inValue.Body.creditCardNumber = creditCardNumber;
            AmiamStore.ServiceReference1.DetailtsOfAllInvitesResponse retVal = ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).DetailtsOfAllInvites(inValue);
            return retVal.Body.DetailtsOfAllInvitesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.DetailtsOfAllInvitesResponse> AmiamStore.ServiceReference1.payWebServiceSoap.DetailtsOfAllInvitesAsync(AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequest request) {
            return base.Channel.DetailtsOfAllInvitesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmiamStore.ServiceReference1.DetailtsOfAllInvitesResponse> DetailtsOfAllInvitesAsync(string creditCardNumber) {
            AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequest inValue = new AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequest();
            inValue.Body = new AmiamStore.ServiceReference1.DetailtsOfAllInvitesRequestBody();
            inValue.Body.creditCardNumber = creditCardNumber;
            return ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).DetailtsOfAllInvitesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailResponse AmiamStore.ServiceReference1.payWebServiceSoap.SendPurchaseClearanceOnEmail(AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequest request) {
            return base.Channel.SendPurchaseClearanceOnEmail(request);
        }
        
        public void SendPurchaseClearanceOnEmail(string ToEmail, string ToName) {
            AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequest inValue = new AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequest();
            inValue.Body = new AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequestBody();
            inValue.Body.ToEmail = ToEmail;
            inValue.Body.ToName = ToName;
            AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailResponse retVal = ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).SendPurchaseClearanceOnEmail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailResponse> AmiamStore.ServiceReference1.payWebServiceSoap.SendPurchaseClearanceOnEmailAsync(AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequest request) {
            return base.Channel.SendPurchaseClearanceOnEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailResponse> SendPurchaseClearanceOnEmailAsync(string ToEmail, string ToName) {
            AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequest inValue = new AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequest();
            inValue.Body = new AmiamStore.ServiceReference1.SendPurchaseClearanceOnEmailRequestBody();
            inValue.Body.ToEmail = ToEmail;
            inValue.Body.ToName = ToName;
            return ((AmiamStore.ServiceReference1.payWebServiceSoap)(this)).SendPurchaseClearanceOnEmailAsync(inValue);
        }
    }
}
